name: Upload Ready IPA to TestFlight

# Скрипт будет запускаться по кнопке вручную
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest # Нужен Mac, чтобы работала утилита Apple

    steps:
      - name: 📥 Скачивание файлов из репозитория
        uses: actions/checkout@v4

      - name: 🚀 Отправка файла в TestFlight
        env:
          API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          # 1. Готовим ключи для Apple
          mkdir -p ~/.appstoreconnect/private_keys/
          echo "$API_KEY" > ~/.appstoreconnect/private_keys/AuthKey_${KEY_ID}.p8
          
          # 2. Ищем ipa файл в репозитории
          IPA_FILE=$(find . -name "*.ipa" | head -n 1)
          echo "Готовлю к отправке файл: $IPA_FILE"
          
          # 3. Отправляем в TestFlight
          xcrun altool --upload-app \
                       --type ios \
                       --file "$IPA_FILE" \
                       --apiKey $KEY_ID \
                       --apiIssuer $ISSUER_ID
